# Generated by Django 3.0.8 on 2020-07-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='titulo',
            new_name='title',
        ),
    ]
