# Generated by Django 3.0.8 on 2020-08-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20200727_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.AlterField(
            model_name='servicio',
            name='image',
            field=models.ImageField(upload_to='servicios'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
